server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/snippets}
    username: ${SPRING_DATASOURCE_USERNAME:snippets}
    password: ${SPRING_DATASOURCE_PASSWORD:snippets}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      # Para mapear JSON a jsonb en Postgres con Hibernate 6
      hibernate.type.preferred_json_sql_type: JSONB
      # Evita l√≠os de huso horario (opcional)
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-c2gyaqqsxa2v3nig.us.auth0.com/}


streams:
  formatting: ps.formatting
  linting: ps.linting

asset:
  service:
    base-url: ${ASSET_SERVICE_BASE_URL:http://localhost:8080}

execution:
  base-url: ${EXECUTION_BASE_URL:http://localhost:8082}

authorization:
  service:
    url: ${AUTHORIZATION_BASE_URL:http://authorization:8081}

# Auth0
auth0:
  domain: ${AUTH0_DOMAIN:dev-c2gyaqqsxa2v3nig.us.auth0.com}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE:https://snippet-manager}

newrelic:
  logs:
    enabled: true
