naming:
  ClassNaming:
    active: true
    # Empieza con may√∫scula y NO permite [A-Z]{2}
    classPattern: '^(?!.*[A-Z]{2})[A-Z][A-Za-z0-9]*$'

  FunctionNaming:
    active: true
    # lowerCamelCase, sin AA
    functionPattern: '^(?!.*[A-Z]{2})[a-z][A-Za-z0-9]*$'
    ignoreAnnotated: ['Test']   # permite nombres raros en tests

  VariableNaming:
    active: true
    # lowerCamelCase, sin AA
    variablePattern: '^(?!.*[A-Z]{2})[a-z][A-Za-z0-9]*$'

style:
  MaxLineLength:
    active: true
    maxLineLength: 400
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false

  ReturnCount:
    active: true
    max: 10

  ThrowsCount:
    active: true
    max: 5

  LoopWithTooManyJumpStatements:
    active: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 15
    constructorThreshold: 10
    ignoreDefaultParameters: true

  CyclomaticComplexMethod:
    active: true
    threshold: 25

  TooManyFunctions:
    active: true
    thresholdInClasses: 40
    thresholdInInterfaces: 30

  LongMethod:
    active: true
    threshold: 120

  LargeClass:
    active: true
    threshold: 5000

exceptions:
  TooGenericExceptionCaught:
    active: true
    excludes: ['**/runner/src/main/kotlin/org/printscript/runner/**']
    allowedExceptionNameRegex: '^(_|(ignore|expected).*)'